name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@v3
        with:
          command: deploy
        env:
          
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_REGION: lhr
          FLY_ORG_NAME: personal
          FLY_APP_NAME: requestperform
